Repository pagopa/cstar-infrastructure, pull requests merged in 2021-09, with the labels that each got.

#144 Do not connect to db replica
  src/aks/locals.tf
Labels: status: applied

#145 Disable checkiban proxy
  src/aks/subscriptions/PROD-CSTAR/terraform.tfvars
  src/scripts/restart-pods.sh
Labels: status: applied

#146 🔒️ Disable db public access
  src/database.tf
  src/scripts/base_64_decode.sh
  src/scripts/restart-pods.sh
Labels: status: applied

#147 Add rtd log
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
Labels: status: applied

#148 Change policy get-instrument status
  src/api/bpd_hb_payment_instruments/original/getstatuspaymentinstrumenthb_policy.xml.tpl
Labels: status: applied

#149 [#CEN-513] Add PDND whitelist ip
  src/database.tf
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/variables.tf
Labels: status: applied

#152 Scale up envs
  src/aks/subscriptions/UAT-CSTAR/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/network.tf
  src/variables.tf
Labels: status: applied

#153 Add aks variable postgres replica connection
  src/aks/locals.tf
  src/aks/variables.tf
Labels: status: applied

#155 HB Payment Instrument getStatusPaymentInstrument Original aligned to …
  src/api/bpd_hb_payment_instruments/original/getstatuspaymentinstrumenthb_policy.xml.tpl
Labels: status: apply in progress

#157 Change openapi definition getstatuspaymentinstrumenth
  src/api/bpd_hb_payment_instruments/original/openapi.json.tpl
Labels: status: applied

#159 New entry route table haproxy
  src/network.tf
Labels: status: applied

#161 Apim with redis id
  src/README.md
  src/api.tf
Labels: status: applied

#158 HB Payment Instrument deletePaymentInstrument V2 aligned to PROD
  src/api/bpd_hb_payment_instruments/v2/deldeletepaymentinstrumenthb_policy.xml.tpl
Labels: status: applied

#162 Monitor api
  src/README.md
  src/api.tf
  src/api/monitor/mock_policy.xml
  src/api/monitor/openapi.json.tpl
Labels: status: applied

#160 Fix notification manager configs and text message
  src/aks/bpd_configmaps.tf
  src/aks/configmaps/bpdmsnotificationmanager/NOTIFICATION_SERVICE_END_PERIOD_GP_MARKDOWN_KO.txt
  src/aks/configmaps/bpdmsnotificationmanager/NOTIFICATION_SERVICE_END_PERIOD_GP_MARKDOWN_OK.txt
  src/aks/configmaps/bpdmsnotificationmanager/NOTIFICATION_SERVICE_END_PERIOD_GP_MARKDOWN_OK_SUPERCASHBACK.txt
  src/aks/configmaps/bpdmsnotificationmanager/NOTIFICATION_SERVICE_END_PERIOD_MARKDOWN.txt
  src/aks/configmaps/bpdmsnotificationmanager/NOTIFICATION_SERVICE_NOTIFY_PAYMENT_WINNERS_MARKDOWN_KO.txt
  src/aks/configmaps/bpdmsnotificationmanager/NOTIFICATION_SERVICE_NOTIFY_PAYMENT_WINNERS_MARKDOWN_KO_TECHNICAL.txt
  src/aks/configmaps/bpdmsnotificationmanager/NOTIFICATION_SERVICE_NOTIFY_PAYMENT_WINNERS_MARKDOWN_OK.txt
  src/aks/configmaps/bpdmsnotificationmanager/NOTIFICATION_SERVICE_NOTIFY_PAYMENT_WINNERS_MARKDOWN_OK_TECHNICAL.txt
  src/aks/configmaps/bpdmsnotificationmanager/TEST.txt
  src/aks/subscriptions/DEV-CSTAR/terraform.tfvars
  src/aks/subscriptions/PROD-CSTAR/terraform.tfvars
  src/aks/subscriptions/UAT-CSTAR/terraform.tfvars
Labels: status: applied

#164 Align rbac to azure ad groups
  src/aks/rbac.tf
Labels: status: applied

#132 Prod db migration scripts
  src/env/prod/terraform.tfvars
  src/psql/flyway.sh
  src/psql/migrations/PROD-CSTAR/bpd/V4__change_db_link.sql
  src/psql/migrations/PROD-CSTAR/bpd/V5__set_dblink_ssl_require.sql
  src/psql/migrations/PROD-CSTAR/bpd/V6__bpd_usr_MONITORING_PDND.sql
  src/psql/migrations/PROD-CSTAR/bpd/V7__bpd_usr_MONITORING_SIA.sql
  src/psql/migrations/PROD-CSTAR/bpd/V8__bpd_usr_MONITORING_OPERATION.sql
  src/psql/migrations/PROD-CSTAR/fa/V1__fa.pre.sql
  src/psql/migrations/PROD-CSTAR/fa/V2__fa.post.sql
  src/psql/migrations/PROD-CSTAR/postgres/V3__update_user_password.sql
  src/psql/migrations/PROD-CSTAR/postgres/V4__usr_MONITORING_PDND.sql
  src/psql/migrations/PROD-CSTAR/postgres/V5__usr_MONITORING_SIA.sql
  src/psql/migrations/PROD-CSTAR/postgres/V6__usr_MONITORING_OPERATION.sql
  src/psql/migrations/PROD-CSTAR/rtd/V3__rtd_change_db_link.sql
  src/psql/migrations/PROD-CSTAR/rtd/V4__set_dblink_ssl_require.sql
  src/psql/migrations/PROD-CSTAR/rtd/V5__rtd_usr_MONITORING_PDND.sql
  src/psql/migrations/PROD-CSTAR/rtd/V6__rtd_usr_MONITORING_SIA.sql
  src/psql/migrations/PROD-CSTAR/rtd/V7__rtd_usr_MONITORING_OPERATION.sql
  src/psql/migrations/UAT-CSTAR/bpd/V19__bpd_usr_MONITORING_PDND.sql
  src/psql/migrations/UAT-CSTAR/bpd/V20__bpd_usr_MONITORING_SIA.sql
  src/psql/migrations/UAT-CSTAR/bpd/V21__bpd_usr_MONITORING_OPERATION.sql
  src/psql/migrations/UAT-CSTAR/fa/V3__fa_usr_MONITORING_PDND.sql
  src/psql/migrations/UAT-CSTAR/fa/V4__fa_usr_MONITORING_SIA.sql
  src/psql/migrations/UAT-CSTAR/fa/V5__fa_usr_MONITORING_OPERATION.sql
  src/psql/migrations/UAT-CSTAR/postgres/V3__usr_MONITORING_PDND.sql
  src/psql/migrations/UAT-CSTAR/postgres/V4__usr_MONITORING_SIA.sql
  src/psql/migrations/UAT-CSTAR/postgres/V5__usr_MONITORING_OPERATION.sql
  src/psql/migrations/UAT-CSTAR/rtd/V3__rtd_usr_MONITORING_PDND.sql
  src/psql/migrations/UAT-CSTAR/rtd/V4__rtd_usr_MONITORING_SIA.sql
  src/psql/migrations/UAT-CSTAR/rtd/V5__rtd_usr_MONITORING_OPERATION.sql
Labels: status: applied

#168 Remove tags alerts db
  src/README.md
  src/database.tf
Labels: status: applied

#166 Fix api blobstorage
  src/api.tf
Labels: status: applied

#169 Temporary host for the get-hashed-pans api in production only
  src/api.tf
Labels: status: applied

#165 App gw ssl profiles
  src/.terraform.lock.hcl
  src/README.md
  src/api.tf
  src/main.tf
  src/modules/app_gw/main.tf
  src/modules/app_gw/variables.tf
  src/network.tf
Labels: status: applied

#170 Add key vault policy fo developers
  src/security.tf
Labels: status: applied

#171 [CEN-622] Reschedule CONSAP flow to every monday, starting from 20/09
  src/k8s/bpd_configmaps.tf
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
Labels: status: applied

#174 Disable dev alert
  src/env/dev/terraform.tfvars
Labels: status: applied

#176 enable diagnostic settings for the pp gw
  src/README.md
  src/main.tf
  src/modules/app_gw/README.md
  src/modules/app_gw/main.tf
  src/modules/app_gw/outputs.tf
  src/modules/app_gw/variables.tf
  src/monitor.tf
  src/network.tf
  src/outputs.tf
  src/security.tf
Labels: status: applied

#181 Add extra permission on k8s for devs
  src/k8s/rbac.tf
Labels: status: applied

#179 [CEN-652] Fix Configmap of Notification Manager Microservice
  src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
  src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
Labels: status: applied, env: dev, env: uat, env: prod

#182 forward the app gw logs to the security storage account
  src/README.md
  src/modules/app_gw/main.tf
  src/modules/app_gw/variables.tf
  src/network.tf
  src/security.tf
Labels: status: applied

#183 [CEN-666] Fix Postgres Configuration
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod

#187 Renaming devops service principal
  src/modules/app_gw/main.tf
  src/network.tf
  src/security.tf
Labels: status: applied

#201 [CEN-745] Config Map for FA ms Transaction
  src/k8s/fa_configmaps.tf
  src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
  src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
  src/k8s/variables.tf
Labels: status: applied, env: dev, env: uat, env: prod

#203 [CEN-748] FA Ingress
  src/k8s/fa_ingress.tf
Labels: status: applied, env: dev, env: uat, env: prod
