Repository pagopa/cstar-infrastructure, pull requests merged in 2021-10, with the labels that each got.

#212 [CEN-768] Fix apim custom domain certificate
  src/api.tf
  src/network.tf
Labels: status: applied, env: dev, env: uat, env: prod

#213 Add aks admins dev env
  src/aks.tf
Labels: status: ready to apply, env: dev

#211 Send apim diagnostic settings to prod-sec workspace
  src/api.tf
Labels: status: ready to apply, env: prod

#210 [CEN-767] Scale in app gateway prod
  src/env/prod/terraform.tfvars
Labels: status: ready to apply, env: prod

#215 [CEN-780] Configmap for Enrollment Microservice
  src/k8s/fa_configmaps.tf
  src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
  src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
  src/k8s/variables.tf
Labels: status: applied, env: dev, env: uat, env: prod

#218 CEN-797] Align management dns record
  src/api.tf
  src/dns_public.tf
  src/network.tf
Labels: status: applied, env: dev, env: uat, env: prod

#219 [CEN-801] Disable WAF 920300 Request Missing an Accept Header
  src/api.tf
  src/modules/app_gw/README.md
  src/modules/app_gw/main.tf
  src/modules/app_gw/outputs.tf
  src/modules/app_gw/variables.tf
  src/network.tf
Labels: status: applied, env: dev, env: uat, env: prod
