Repository pagopa/cstar-infrastructure, pull requests merged in 2022-11, with the labels that each got.

#648 feat: [RTD-702] Add alert on remove ade ack file
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#649 feat: [RTD-813] Add malformed chunk alert
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#646 feat: [RTD-716] Overnight bulk delete in testing environments
  src/domains/tae-app/08_pipeline.tf
  src/domains/tae-app/99_variables.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#650 feat: [RTD-843] Add failed decryption alert
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#651 feat: IID-45 Add token validation to BE IO only for UAT
  src/domains/idpay-app/api_product/app_io/policy_io.xml.tpl
Labels: dev, uat, applied dev, applied uat, idpay-app

#652 feat: [RTD-844] Add alert whenever there is no data in decrypted file
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#653 chore: [RTD-791] Add configmap and secret for pi event processor
  src/k8s/README.md
  src/k8s/rtd_configmaps.tf
  src/k8s/rtd_secrets.tf
  src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
  src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
  src/k8s/variables.tf
Labels: dev, uat, prod, applied dev, applied uat, applied prod

#657 feat: [RTD-852] Wrong encrypted name format alert
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#654 feat: [RTD-771] Enable diagnostic settings on TAE Azure Data Factory
  src/domains/tae-app/08_pipeline.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#658 feat: [RTD-740] Add ACK ingestor pipeline failure alert
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#656 feat: [RTD-856] Provisioning rtd eventhub connection string to idpay kv
  src/domains/idpay-common/01_keyvault_external_secrets.tf
  src/domains/idpay-common/99_variables.tf
  src/domains/idpay-common/README.md
  src/domains/idpay-common/env/dev/terraform.tfvars
  src/domains/idpay-common/env/prod/terraform.tfvars
  src/domains/idpay-common/env/uat/terraform.tfvars
Labels: applied in all environments, dev, uat, prod, idpay-common

#660 feat: [RTD-739] Add aggregates ingestor failure alert
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#661 feat: [RTD-855] Set sink throughput cap
  src/domains/tae-app/08_pipeline.tf
  src/domains/tae-app/99_variables.tf
  src/domains/tae-app/README.md
  src/domains/tae-app/env/dev/terraform.tfvars
  src/domains/tae-app/env/prod/terraform.tfvars
  src/domains/tae-app/env/uat/terraform.tfvars
  src/domains/tae-app/pipelines/ackIngestor.dataflow
  src/domains/tae-app/pipelines/bulkDeleteAggregates.dataflow
Labels: no merge

#655 feat: [RTD-861] Add diagnostic settings to PROD APIM
  src/core/README.md
  src/core/observability.tf
Labels: applied in all environments

#665 feat: [RTD-897] Add unauthorized failed upload alert
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#668 chore: [RTD-899] Add index on name (fileregister)
  src/core/env/prod/terraform.tfvars
  src/core/rtd_database.tf
Labels: applied in all environments, dev, uat, prod

#670 fix: Added missing pi event processor ingress mapping
  src/k8s/rtd_ingress.tf
Labels: applied in all environments, dev, uat, prod, applied dev, applied uat, applied prod

#671 fix: [RTD-911] Remove redundant alert on pipelines failure
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#667 feat: [RTD-898] Add service unavailable failed upload alert
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#666 fix: Set bearer as security schema for wallet api
  src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml
  src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml.tpl
Labels: applied in all environments

#659 feat: [ISB-575] Updated k8s config maps for RTD queues
  src/domains/idpay-app/08_k8s_configmaps.tf
Labels: applied in all environments, idpay-app

#677 fix: [RTD-920] Exclude manual trigger from pipeline failure query for alerts
  src/domains/tae-app/00_monitor.tf
Labels: applied in all environments

#673 chore: [RTD-889] add parameterized source throughput in dataflows
  src/domains/tae-app/08_pipeline.tf
  src/domains/tae-app/pipelines/ackIngestor.dataflow
  src/domains/tae-app/pipelines/bulkDeleteAggregates.dataflow
Labels: applied in all environments

#678 feat: [RTD-879] add filereports collection to cosmos mongodb
  src/core/README.md
  src/core/rtd_database.tf
Labels: applied in all environments

#675 chore: [RTD-910] Set negative ttl on aggregates collection
  src/domains/tae-common/03_database.tf
Labels: applied in all environments

#679 feat: [RTD-921] add file-reporter path to k8s ingress
  src/k8s/rtd_ingress.tf
Labels: applied in all environments

#681 chore: [RTD-928] Add retries in aggregates ingestor copy activities
  src/domains/tae-app/08_pipeline.tf
  src/domains/tae-app/99_variables.tf
  src/domains/tae-app/README.md
  src/domains/tae-app/env/dev/terraform.tfvars
  src/domains/tae-app/env/prod/terraform.tfvars
  src/domains/tae-app/env/uat/terraform.tfvars
  src/domains/tae-app/pipelines/aggregatesIngestor.json.tpl
  src/domains/tae-app/pipelines/aggregatesIngestorTesting.json.tpl
Labels: applied in all environments

#684 fix: [RTD-934] Fix missing idpay secrets
  src/domains/idpay-app/01_keyvault.tf
  src/domains/idpay-app/README.md
Labels: applied in all environments, dev, uat, prod, applied dev, applied uat, applied prod, idpay-app

#687 feat: [RTD-798] Add alert for file permanence in ade/in
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/99_variables.tf
  src/domains/tae-app/README.md
  src/domains/tae-app/env/prod/terraform.tfvars
Labels: prod, applied prod

#683 feat: [RTD-805] Add hashpan v3 to get hashpan/par tuples
  src/core/README.md
  src/core/api/rtd_payment_instrument_manager/get-hashed-pans-policy-rev3.xml.tpl
  src/core/api_rtd.tf
Labels: applied in all environments, dev, uat, prod, applied dev, applied uat, applied prod

#674 feat: [RTD-860] Enable Diagnostic Settings on PROD APPGW
  src/core/README.md
  src/core/observability.tf
Labels: prod, applied prod

#682 feat: IREER-190 added rankingTopic
  src/domains/idpay-app/.terraform.lock.hcl
  src/domains/idpay-app/08_k8s_configmaps.tf
  src/domains/idpay-common/.terraform.lock.hcl
  src/domains/idpay-common/env/dev/terraform.tfvars
  src/domains/idpay-common/env/prod/terraform.tfvars
  src/domains/idpay-common/env/uat/terraform.tfvars
Labels: applied dev, idpay-app

#689 feat: IGR-69 update hostname io
  src/domains/idpay-app/api_product/app_io/policy_io.xml.tpl
Labels: applied dev, idpay-app

#672 feat: ISB-571 update onboarding api
  src/domains/idpay-app/api/idpay_iban/openapi.iban.yml
  src/domains/idpay-app/api/idpay_iban/openapi.iban.yml.tpl
  src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml
  src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml.tpl
  src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml
  src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml.tpl
  src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml
  src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml.tpl
Labels: applied dev, idpay-app

#693 feat: IPE-596 aggiornamento swagger per api download lista errori
  src/domains/idpay-app/04_apim_api_portal.tf
  src/domains/idpay-app/api/idpay_initiative/get-disp-errors.xml.tpl
  src/domains/idpay-app/api/idpay_initiative/openapi.initiative.yml
  src/domains/idpay-app/api/idpay_initiative/put-initiative-approve.xml.tpl
  src/domains/idpay-app/api/idpay_initiative/put-initiative-publish.xml.tpl
  src/domains/idpay-common/03_database.tf
Labels: applied in all environments, idpay-app, idpay-common

#691 feat: [RTD-847] Add file report endpoint
  src/core/README.md
  src/core/api/rtd_filereporter/get-file-report-policy.xml.tpl
  src/core/api/rtd_filereporter/openapi.yml
  src/core/api_rtd.tf
Labels: applied in all environments, dev, uat, prod

#663 fix: [RTD-867] Reduce pipelines logs to essential ones
  src/domains/tae-app/08_pipeline.tf
Labels: prod, applied prod

#686 feat: [RTD-877] create event hub and related consumer-producer policy
  src/domains/rtd-app/env/dev/terraform.tfvars
  src/domains/rtd-app/env/prod/terraform.tfvars
  src/domains/rtd-app/env/uat/terraform.tfvars
  src/k8s/README.md
  src/k8s/rtd_secrets.tf
  src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
  src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
Labels: applied in all environments, dev, uat, prod, applied dev, applied uat, applied prod, rtd-app

#697 feat: [RTD-922] Add get public key tkm by using api pagopa platform
  src/core/README.md
  src/core/api/rtd_payment_instrument_token/get-token-public-key-policy.xml
  src/core/api/rtd_payment_instrument_token/openapi.yml
  src/core/api_rtd.tf
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/core/key_vault_0.tf
  src/core/variables.tf
Labels: dev, applied dev, core

#696 feat: [RTD-943] Remove stub and call file reporter endpoint
  src/core/api/rtd_filereporter/get-file-report-policy.xml.tpl
  src/core/api/rtd_filereporter/openapi.yml
Labels: applied in all environments, dev, uat, prod

#698 feat: [RTD-682] Expose Acquirer API to upload tokenpan files
  src/core/api/rtd_payment_instrument_token/openapi.yml
  src/core/api/rtd_payment_instrument_token/upload-token-file-policy.xml
  src/core/api_rtd.tf
Labels: dev, applied dev, core
