Repository pagopa/cstar-infrastructure, pull requests merged in 2022-09, with the labels that each got.

#526 New policy eventhub tkm-write-update
  src/core/env/dev/terraform.tfvars
Labels: status: applied

#507 Ireer 130 creazione coda via terraform
  src/domains/idpay-common/04_service_bus.tf
  src/domains/idpay-common/99_variables.tf
  src/domains/idpay-common/README.md
  src/domains/idpay-common/env/dev/terraform.tfvars
Labels: status: applied, env: dev

#508 IREER-132 - Add generic error topic
  src/domains/idpay-common/env/dev/terraform.tfvars
  src/domains/idpay-common/env/uat/terraform.tfvars
Labels: status: applied, env: dev

#528 IPE-195-creazione-policy-su-apim-per-esposizione-rotte-upload-file
  src/domains/idpay-app/04_apim_api_portal.tf
  src/domains/idpay-app/README.md
  src/domains/idpay-app/api/idpay_group/get-group-status.xml.tpl
  src/domains/idpay-app/api/idpay_group/openapi.group.yml
  src/domains/idpay-app/api/idpay_group/put-group-upload.xml.tpl
Labels: status: applied, env: dev

#529 [TAE-179] Create Data Explorer cluster
  src/core/README.md
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/core/observability.tf
  src/core/variables.tf
Labels: status: applied, env: dev

#530 [TAE-186] Add DEXP db
  src/domains/tae-common/00_monitor.tf
  src/domains/tae-common/99_variables.tf
  src/domains/tae-common/README.md
  src/domains/tae-common/env/dev/terraform.tfvars
  src/domains/tae-common/env/prod/terraform.tfvars
  src/domains/tae-common/env/uat/terraform.tfvars
Labels: status: applied, env: dev

#531 [TAE-185] Add linked service for tae DB of Data Explorer
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/06_linked_service.tf
  src/domains/tae-app/99_variables.tf
  src/domains/tae-app/README.md
  src/domains/tae-app/env/dev/terraform.tfvars
Labels: status: applied, env: dev

#532 [TAE-187] Add script to create tables in TAE db in Data Explorer
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
  src/domains/tae-app/scripts/create_tables.dexp
Labels: status: applied, env: dev

#533 [TAE-180] Ingest aggregates in Data Explorer
  src/domains/tae-app/07_datasets.tf
  src/domains/tae-app/README.md
  src/domains/tae-app/pipelines/aggregatesIngestor.json
  src/domains/tae-app/pipelines/aggregatesSchema.json
  src/domains/tae-common/04_datafactory.tf
Labels: status: applied, env: dev

#534 [TAE-181] Send acks to Data Explorer
  src/domains/tae-app/06_linked_service.tf
  src/domains/tae-app/07_datasets.tf
  src/domains/tae-app/08_pipeline.tf
  src/domains/tae-app/README.md
  src/domains/tae-app/pipelines/ackIngestor.dataflow
Labels: status: applied, env: dev

#537 [TAE-188] Promote Data Explorer to UAT and PROD
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/07_datasets.tf
  src/domains/tae-app/env/prod/terraform.tfvars
  src/domains/tae-app/env/uat/terraform.tfvars
  src/domains/tae-app/pipelines/aggregatesIngestor.json
  src/domains/tae-app/scripts/create_tables.dexp
  src/domains/tae-common/env/prod/terraform.tfvars
  src/domains/tae-common/env/uat/terraform.tfvars
Labels: status: applied, env: uat, env: prod

#540 [TAE-18] Clean Temp DB
  src/core/env/dev/terraform.tfvars
  src/domains/tae-app/08_pipeline.tf
  src/domains/tae-app/pipelines/ackIngestor.dataflow
  src/domains/tae-app/pipelines/aggregatesIngestor.json
Labels: status: applied, env: dev, env: uat, env: prod

#539 [RTD-487] Added PROD variables for rtd
  src/domains/rtd-common/01_keyvault_0.tf
  src/domains/rtd-common/99_main.tf
  src/domains/rtd-common/README.md
  src/domains/rtd-common/env/prod/backend.ini
  src/domains/rtd-common/env/prod/backend.tfvars
  src/domains/rtd-common/env/prod/terraform.tfvars
Labels: status: apply in progress, env: prod

#536 IPE-253 - publish initiative refund API
  src/domains/idpay-app/04_apim_api_portal.tf
  src/domains/idpay-app/api/idpay_group/openapi.group.yml
  src/domains/idpay-app/api/idpay_initiative/openapi.initiative.yml
  src/domains/idpay-app/api/idpay_initiative/put-initiative-refund-draft.xml.tpl
  src/domains/idpay-app/api/idpay_initiative/put-initiative-refund.xml.tpl
Labels: status: applied, env: dev

#541 ISB-357-creazione-coda-per-le-notifiche-diverse-dallonboarding
  src/domains/idpay-common/env/dev/terraform.tfvars
  src/domains/idpay-common/env/uat/terraform.tfvars
Labels: status: applied, env: dev

#548 IID-33 update cdn rule
  src/domains/idpay-common/04_cdn.tf
  src/domains/idpay-common/99_main.tf
  src/domains/idpay-common/env/dev/terraform.tfvars
  src/domains/idpay-common/env/uat/terraform.tfvars
Labels: status: applied, env: dev

#480 IID-30 - update collection configuration
  src/domains/idpay-common/.terraform.lock.hcl
  src/domains/idpay-common/03_database.tf
  src/domains/idpay-common/README.md
Labels: status: applied, env: dev

#552 [RTD-521] Restore key hash in container name
  src/core/api/rtd_csv_transaction/create-sas-token-policy.xml
Labels: status: applied, env: dev, env: uat, env: prod

#556 [RTD-518] Create Support Tables in Data Explorer
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/08_pipeline.tf
  src/domains/tae-app/99_variables.tf
  src/domains/tae-app/README.md
  src/domains/tae-app/env/dev/terraform.tfvars
  src/domains/tae-app/env/prod/terraform.tfvars
  src/domains/tae-app/env/uat/terraform.tfvars
  src/domains/tae-app/scripts/create_tables.dexp
Labels: status: applied, env: dev, env: uat, env: prod

#554 [RTD-520] Added indexes to senderauth collection
  src/core/rtd_database.tf
Labels: status: applied, env: dev, env: uat, env: prod

#558 [RTD-528] Fix batch size in Dataflow
  src/domains/tae-app/pipelines/ackIngestor.dataflow
Labels: status: applied, env: dev, env: uat, env: prod

#562 [RTD-535] Sender AdE ACK directory from file name
  src/core/api/rtd_senderack_download_file/azureblob_policy.xml
Labels: status: applied, env: dev, env: uat, env: prod

#563 [RTD-539] Enrolled pim producer config
  src/domains/idpay-app/01_keyvault.tf
  src/domains/idpay-app/08_k8s_configmaps.tf
  src/domains/idpay-app/99_variables.tf
  src/domains/idpay-app/README.md
  src/domains/idpay-app/env/dev/terraform.tfvars
  src/domains/idpay-app/env/uat/terraform.tfvars
  src/k8s/README.md
  src/k8s/rtd_configmaps.tf
  src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
  src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
  src/k8s/variables.tf
Labels: status: applied, env: dev, env: uat, env: prod

#564 [RTD-561] Alter ABI table schema [Data Explorer]
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/scripts/create_tables.dexp
Labels: applied in all environments, dev, uat, prod

#559 [RTD-522] Adapted apim get sender ack list from list of sender codes
  src/core/api/rtd_senderack_filename_list/policy.xml
Labels: applied in all environments, dev, uat, prod

#560 Iid 31 allineamento config map k8s
  src/domains/idpay-app/08_k8s_configmaps.tf
  src/domains/idpay-app/README.md
Labels: applied dev

#577 [RTD-634] TKM kafka queue and connection string secrets
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/k8s/README.md
  src/k8s/rtd_secrets.tf
  src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
  src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
Labels: applied in all environments

#578 [RTD-634] tkm kafka secret
  src/k8s/rtd_secrets.tf
Labels: applied in all environments

#579 [RTD-646] Fix TPAY1 FC
  src/core/api/rtd_abi_to_fiscalcode/policy.xml.tpl
Labels: applied in all environments

#575 feat: idpay's transaction indexes updated
  src/domains/idpay-common/03_database.tf
Labels: applied dev
