Repository pagopa/cstar-infrastructure, pull requests merged in 2022-10, with the labels that each got.

#576 feat: [RTD-607] Change deposited file container in integration endpoint
  src/core/api/rtd_deposited_file_check/azureblob_policy.xml
  src/core/api_rtd.tf
  src/core/sftp.tf
Labels: applied in all environments

#568 feat: [RTD-553] Expose endpoint to explicitly ack AdE errors
  src/core/README.md
  src/core/api/rtd_senderack_correct_download_ack/openapi.yml
  src/core/api/rtd_senderack_correct_download_ack/policy.xml
  src/core/api_rtd.tf
Labels: applied in all environments

#585 feat: [RTD-592] Add sender-auth authorization call to download ack
  src/core/api/rtd_senderack_download_file/azureblob_policy.xml
Labels: applied dev, applied uat, applied prod

#589 feat: IREER-156: storing rtd-trx topic jaas-config into idpay keyvault
  src/domains/idpay-common/.terraform.lock.hcl
  src/domains/idpay-common/04_cdn.tf
  src/domains/idpay-common/04_eventhub.tf
  src/domains/idpay-common/99_locals.tf
  src/domains/idpay-common/README.md
Labels: dev, uat, applied dev

#593 fix: [RTD-717] Mocking salt to PM 503
  src/core/api/rtd_payment_instrument_manager/get-hash-salt_policy.xml.tpl
  src/core/api_rtd.tf
Labels: applied in all environments

#570 feat: IPE-419-aggiornamento-policy-token-exchange-apim
  src/domains/idpay-app/08_k8s_configmaps.tf
  src/domains/idpay-app/api/idpay_token_exchange/jwt_exchange.xml.tpl
  src/domains/idpay-app/api/idpay_token_exchange/jwt_token_test.xml.tpl
  src/domains/idpay-app/api_product/portal_api/policy_portal.xml.tpl
Labels: dev, uat, applied dev, applied uat

#590 feat: IREER-163 reward-notification collections
  src/domains/idpay-common/03_database.tf
Labels: dev, uat, applied dev

#591 feat: [RTD-709] Add bulk delete pipeline
  src/domains/tae-app/08_pipeline.tf
  src/domains/tae-app/README.md
  src/domains/tae-app/pipelines/bulkDeleteAggregates.dataflow
  src/domains/tae-app/pipelines/bulkDeleteAggregates.json
Labels: applied in all environments

#596 feat: storing redis connection url into keyvault
  src/domains/idpay-common/05_redis_cache.tf
  src/domains/idpay-common/README.md
Labels: dev, uat, applied dev, applied uat

#602 feat: [RTD-734] Enable aggregates ingestor trigger in PROD environment
  src/domains/tae-app/env/prod/terraform.tfvars
Labels: applied in all environments

#600 fix: [CSFA-72] Error in "fa_autoscaling_specs" UAT variable
  src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
Labels: uat, applied uat

#597 feat: ISB-484-aggiornamento-script-terraform
  src/domains/idpay-app/env/uat/terraform.tfvars
  src/domains/idpay-common/03_database.tf
Labels: dev, uat, applied dev, applied uat

#604 chore: [TAE-189] Add action group to send alerts to operations
  src/domains/tae-app/00_key_vault.tf
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: prod, applied prod

#605 chore: [RTD-722] Add revoke producer k8s secret
  src/k8s/README.md
  src/k8s/rtd_secrets.tf
  src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
  src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
  src/k8s/variables.tf
Labels: applied in all environments

#606 fix: Fix App IO authentication
  src/domains/idpay-app/04_apim_api_io.tf
  src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml
  src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml.tpl
Labels: dev, uat, applied dev, applied uat

#608 fix: ISB-507-aggiornamento-policy-apim-enrollment
  src/domains/idpay-app/04_apim_api_io.tf
  src/domains/idpay-app/api/idpay_wallet/put-enroll-instrument-policy.xml.tpl
Labels: dev, uat, applied dev, applied uat

#614 fix: pim missing ingress
  src/k8s/rtd_ingress.tf
Labels: applied in all environments

#613 feat: [RTD-764] Add decrypter role name
  src/k8s/rtd_configmaps.tf
Labels: applied in all environments

#611 feat: [RTD-751] Add file register config map
  src/k8s/README.md
  src/k8s/rtd_configmaps.tf
  src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
  src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
  src/k8s/variables.tf
Labels: applied in all environments

#609 feat: [RTD-753] Enable ade ack ingestor on PROD
  src/domains/tae-app/env/prod/terraform.tfvars
  src/domains/tae-app/pipelines/ackIngestor.json
Labels: prod, applied prod

#619 fix: Data explorer change sku to optimize cost in DEV/UAT
  src/core/README.md
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/core/observability.tf
  src/core/variables.tf
Labels: applied in all environments

#618 feat: [RTD-767] Add Sender Auth config map
  src/k8s/README.md
  src/k8s/rtd_configmaps.tf
  src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
  src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
  src/k8s/variables.tf
Labels: applied in all environments

#620 feat: [RTD-594] Add failed authentications alert
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#607 feat: [RTD-569] set policy custom for external file upload
  src/core/api/azureblob/azureblob_authorizative_policy.xml
  src/core/api_rtd.tf
  src/core/observability.tf
Labels: dev, uat, prod, applied dev, applied uat, applied prod

#622 feat: [RTD-604] Add alert on missing internal ID
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#624 fix: fix revoke eventhub connection string fa
  src/k8s/rtd_secrets.tf
Labels: prod, applied prod

#628 feat: IPE-385-definizione-e-pubblicazione-swagger-api
  src/domains/idpay-app/.terraform.lock.hcl
  src/domains/idpay-app/04_apim_api_portal.tf
  src/domains/idpay-app/99_variables.tf
  src/domains/idpay-app/README.md
  src/domains/idpay-app/api/idpay_initiative/get-initiative-statistics.xml.tpl
  src/domains/idpay-app/api/idpay_initiative/openapi.initiative.yml
  src/domains/idpay-app/api/idpay_notification_email/get-institution-user-info-policy.xml.tpl
  src/domains/idpay-app/api/idpay_notification_email/openapi.notification.email.yml
  src/domains/idpay-app/api/idpay_notification_email/post-notify-email-policy.xml.tpl
  src/domains/idpay-app/env/dev/terraform.tfvars
  src/domains/idpay-app/env/prod/terraform.tfvars
  src/domains/idpay-app/env/uat/terraform.tfvars
Labels: dev, uat, prod, applied dev, applied uat

#630 fix: revoked-pi added fa namespace for prod
  src/domains/idpay-app/01_keyvault.tf
  src/domains/idpay-app/99_variables.tf
  src/domains/idpay-app/README.md
  src/domains/idpay-app/env/dev/terraform.tfvars
  src/domains/idpay-app/env/prod/terraform.tfvars
  src/domains/idpay-app/env/uat/terraform.tfvars
Labels: prod

#631 feat(monitoring): [DEVOPS-465] Add new alerts channels
  src/aks-platform/00_monitor.tf
  src/aks-platform/99_locals.tf
  src/aks-platform/README.md
  src/core/README.md
  src/core/key_vault_0.tf
  src/core/observability.tf
  src/domains/idpay-app/00_monitor.tf
  src/domains/idpay-app/99_locals.tf
  src/domains/idpay-app/README.md
  src/domains/idpay-common/00_monitor.tf
  src/domains/idpay-common/README.md
  src/domains/rtd-app/00_monitor.tf
  src/domains/rtd-app/99_locals.tf
  src/domains/rtd-app/README.md
  src/domains/rtd-common/00_monitor.tf
  src/domains/rtd-common/README.md
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/99_locals.tf
  src/domains/tae-app/README.md
  src/domains/tae-common/00_monitor.tf
  src/domains/tae-common/README.md
Labels: applied in all environments

#616 feat: [RTD-772] Add TAE pipeline failure alert
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#633 fix: [RTD-761] Added private zone link between aks platform and eventhub
  src/core/README.md
  src/core/dns_private.tf
Labels: applied dev, applied uat, applied prod, core

#634 fix: [RTD-821] Added eventhub service endpoint to some subnets
  src/aks-platform/03_aks_0.tf
  src/core/network.tf
Labels: applied in all environments, dev, uat, prod, core

#627 feat: [RTD76] PIM downstream queue
  src/domains/rtd-common/00_dns_private.tf
  src/domains/rtd-common/00_network.tf
  src/domains/rtd-common/04_eventhub.tf
  src/domains/rtd-common/99_variables.tf
  src/domains/rtd-common/README.md
  src/domains/rtd-common/env/dev/terraform.tfvars
  src/domains/rtd-common/env/prod/terraform.tfvars
  src/domains/rtd-common/env/uat/terraform.tfvars
Labels: applied in all environments, dev, uat, prod, rtd-common

#629 feat: [RTD-810] Add Operations Zendesk email secret
  src/domains/tae-app/00_key_vault.tf
  src/domains/tae-app/99_variables.tf
  src/domains/tae-app/README.md
  src/domains/tae-app/env/dev/terraform.tfvars
  src/domains/tae-app/env/prod/terraform.tfvars
  src/domains/tae-app/env/uat/terraform.tfvars
Labels: applied in all environments

#626 feat: ISB-527-modifica-config-maps-per-rilascio-uat
  src/domains/idpay-app/.terraform.lock.hcl
  src/domains/idpay-app/08_k8s_configmaps.tf
  src/domains/idpay-app/99_variables.tf
  src/domains/idpay-app/README.md
  src/domains/idpay-app/env/dev/terraform.tfvars
  src/domains/idpay-app/env/uat/terraform.tfvars
Labels: applied in all environments, dev, uat, prod

#623 feat: IREER-178 added iban update outcome + fixed consumer group names
  src/domains/idpay-common/env/dev/terraform.tfvars
  src/domains/idpay-common/env/prod/terraform.tfvars
  src/domains/idpay-common/env/uat/terraform.tfvars
Labels: applied in all environments, dev, uat, prod

#635 feat: IPE-515-aggiornamento-policy-per-informazioni-di-organizzazione
  src/domains/idpay-app/api/idpay_initiative/put-initiative-approve.xml.tpl
  src/domains/idpay-app/api/idpay_initiative/put-initiative-refund-draft.xml.tpl
  src/domains/idpay-app/api/idpay_initiative/put-initiative-refund.xml.tpl
  src/domains/idpay-app/api/idpay_initiative/put-initiative-reject.xml.tpl
Labels: applied in all environments, dev, uat, prod, idpay-app

#621 feat: IPE-481 add new initiative_statistics collection
  src/domains/idpay-common/03_database.tf
Labels: applied in all environments, dev, uat, prod, idpay-common

#632 feat: [RTD-811] Add Operations' Zendesk action group
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#638 feat: [RTD-812] Add Zendesk action to existing alerts
  src/domains/tae-app/00_monitor.tf
Labels: applied in all environments

#639 feat: [RTD-762] Added eventhub connection string to rtd-kv
  src/domains/rtd-app/04_eventhub.tf
  src/domains/rtd-app/README.md
Labels: applied in all environments, dev, uat, prod, applied dev, applied uat, applied prod, rtd-app

#642 chore: [RTD-762] Providing jaas connection string as k8s secrets from new kv
  src/k8s/README.md
  src/k8s/rtd_secrets.tf
  src/k8s/secrets.tf
  src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
  src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
  src/k8s/variables.tf
Labels: applied in all environments, dev, uat, prod, applied dev, applied uat, applied prod

#640 feat: [RTD-703] Add file creation in ade/error alert
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments

#643 feat: [RTD-792] Add Sender Table
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/scripts/create_tables.dexp
Labels: applied in all environments

#644 feat: [RTD-840] Add alert for failed blob upload
  src/domains/tae-app/00_monitor.tf
  src/domains/tae-app/README.md
Labels: applied in all environments
