Repository pagopa/cstar-infrastructure, pull requests merged in 2022-06, with the labels that each got.

#379 Add routing to nexi vnet hub for dev uat
  src/network.tf
Labels: status: applied, env: dev, env: uat

#380 modify scheduler start time
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
Labels: status: applied, env: prod

#377 [TAE-29] Abi to fiscal code api
  src/README.md
  src/api/rtd_abi_to_fiscalcode/openapi.yml.tpl
  src/api/rtd_abi_to_fiscalcode/policy.xml.tpl
  src/api_rtd.tf
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/variables.tf
Labels: status: applied, env: dev, env: uat, env: prod

#376 [CDC-68] Promote health check + IO API in prod
  src/README.md
  src/api/cdc/policy.jwt.xml.tpl
  src/api_cdc.tf
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/variables.tf
Labels: status: applied, env: uat, env: prod

#381 Add dns fot tkm storage
  src/README.md
  src/dns_private.tf
  src/env/dev/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/variables.tf
Labels: status: applied, env: dev, env: uat

#391 [CDC-29] update caching policy to use as a key the bpd-token
  src/api/cdc/get-stato-beneficiario_policy.xml
  src/api/cdc/policy.jwt.xml.tpl
Labels: status: applied, env: uat, env: prod

#389 [TAE-42] API to download the ade ack file name list
  src/README.md
  src/api/rtd_senderack_filename_list/openapi.yml.tpl
  src/api/rtd_senderack_filename_list/policy.xml.tpl
  src/api_rtd.tf
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/variables.tf
Labels: status: apply in progress, env: dev, env: uat

#393 [RTD-164] add file register consumer group in DEV
  src/env/dev/terraform.tfvars
Labels: status: applied, env: dev

#394 [TAE-43] Add sender-ade-ack container in all environments
  src/README.md
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/storage.tf
  src/tae_storage.tf
  src/variables.tf
Labels: status: applied, env: dev, env: uat, env: prod

#395 [TAE-44] Add API to download sender ade ack files
  src/README.md
  src/api/rtd_senderack_download_file/azureblob_policy.xml
  src/api/rtd_senderack_download_file/openapi.json.tpl
  src/api_tae.tf
Labels: status: applied, env: dev, env: uat

#396 [IID-14] Add key vault entry for idpay mongodb connection string
  src/domains/idpay-common/03_database.tf
  src/domains/idpay-common/README.md
Labels: status: applied, env: dev

#399 [TAE-52] Enable Mongo DB access from ADF subnet
  src/database.tf
  src/network.tf
Labels: status: applied, env: dev

#401 [TAE-54] Add ADF Linked Service for Cosmos/Mongo DB
  src/README.md
  src/datafactory.tf
Labels: status: applied, env: dev

#404 [TAE-55] Add pipeline trigger
  src/README.md
  src/tae_pipeline.tf
Labels: status: applied, env: dev

#405 [TAE-56] Create datasets
  src/README.md
  src/database.tf
  src/tae_database.tf
  src/tae_datasets.tf
  src/tae_pipeline.tf
Labels: status: applied, env: dev

#408 [RTD-135] API to test rtd api key
  src/README.md
  src/api/rtd_sender_api_key_check/openapi.yml
  src/api/rtd_sender_api_key_check/policy.xml
  src/api_rtd.tf
Labels: status: applied, env: dev, env: uat

#412 [TAE-11] Create aggregates ingestion pipeline
  src/README.md
  src/database.tf
  src/datafactory.tf
  src/pipelines/aggregatesIngestor.json
  src/tae_database.tf
  src/tae_datasets.tf
  src/tae_pipeline.tf
Labels: status: applied, env: dev

#411 ISB-137-condivisione-swagger
  src/README.md
  src/api_idpay.tf
  src/domains/idpay-app/.terraform.lock.hcl
  src/domains/idpay-app/04_apim_api_io.tf
  src/domains/idpay-app/99_variables.tf
  src/domains/idpay-app/README.md
  src/domains/idpay-app/api/idpay_onboarding_workflow/get-onboarding-status-policy.xml.tpl
  src/domains/idpay-app/api/idpay_onboarding_workflow/put-check-prerequisites-policy.xml.tpl
  src/domains/idpay-app/api/idpay_onboarding_workflow/put-consent-policy.xml.tpl
  src/domains/idpay-app/api/idpay_onboarding_workflow/put-terms-conditions-policy.xml.tpl
  src/domains/idpay-app/api/idpay_onboarding_workflow/swagger.onboarding.json.tpl
  src/domains/idpay-app/api/idpay_timeline/swagger.timeline.json.tpl
  src/domains/idpay-app/api/idpay_wallet/swagger.wallet.json.tpl
  src/domains/idpay-app/api_product/policy.xml.tpl
  src/domains/idpay-app/env/dev/terraform.tfvars
Labels: status: applied, env: dev, env: uat

#410 [RTD-177] Enable feature flag in prod environment for tae.api
  src/env/prod/terraform.tfvars
  src/tae_pipeline.tf
Labels: status: applied, env: prod

#416 [RTD-219] Filter files created in ade container for sftp subscription
  src/sftp.tf
Labels: status: applied, env: dev

#402 Add uat vars for idpay
  src/domains/idpay-common/env/uat/backend.ini
  src/domains/idpay-common/env/uat/backend.tfvars
  src/domains/idpay-common/env/uat/terraform.tfvars
Labels: status: applied, env: uat

#418 [TAE-11] Fix date formats
  src/pipelines/aggregatesIngestor.json
Labels: status: applied, env: dev
