Repository pagopa/cstar-infrastructure, pull requests merged in 2022-08, with the labels that each got.

#466 IPE-192-aggiornamento-swagger-iniziativa
  src/README.md
  src/domains/idpay-app/04_apim_api_portal.tf
  src/domains/idpay-app/api/idpay_initiative/openapi.initiative.yml
  src/domains/idpay-app/api/idpay_initiative/put-initiative-beneficiary-draft.xml.tpl
  src/domains/idpay-app/api/idpay_initiative/put-initiative-beneficiary.xml.tpl
  src/domains/idpay-app/api/idpay_initiative/put-initiative-general.xml.tpl
Labels: status: applied, env: dev

#467 [RTD-349] Add new role assignment for data contributor on SFTP to APIM
  src/README.md
  src/sftp.tf
Labels: status: ready to apply, env: dev, env: uat

#457 Added enrolled-pi eventhub connection uri to idpay kv
  src/domains/idpay-app/01_keyvault.tf
  src/domains/idpay-app/99_variables.tf
  src/domains/idpay-app/README.md
  src/domains/idpay-app/env/dev/terraform.tfvars
  src/domains/idpay-app/env/uat/terraform.tfvars
Labels: status: applied, env: dev

#477 IPE-239 update api and policy for token echange
  src/domains/idpay-app/04_apim_api_token_exchange.tf
  src/domains/idpay-app/api/idpay_token_exchange/jwt_exchange.xml.tpl
Labels: status: applied, env: dev

#474 IREER-117 add new topic for useid-splitter
  src/domains/idpay-common/env/dev/terraform.tfvars
Labels: status: applied, env: dev

#475 [RTD-371] Create new data factory for RTD
  src/domains/rtd-app/.terraform.lock.hcl
  src/domains/rtd-app/02_namespace_domain.tf
  src/domains/rtd-app/04_source_sink.tf
  src/domains/rtd-app/05_datafactory.tf
  src/domains/rtd-app/06_linked_service.tf
  src/domains/rtd-app/07_datasets.tf
  src/domains/rtd-app/08_pipeline.tf
  src/domains/rtd-app/99_main.tf
  src/domains/rtd-app/99_variables.tf
  src/domains/rtd-app/README.md
  src/domains/rtd-app/env/dev/terraform.tfvars
  src/domains/rtd-app/env/uat/terraform.tfvars
  src/domains/rtd-app/pipelines/hashpan_csv_pipeline.json
  src/domains/rtd-common/00_network.tf
  src/domains/rtd-common/02_blob_storage.tf
  src/domains/rtd-common/03_database.tf
  src/domains/rtd-common/04_datafactory.tf
  src/domains/rtd-common/README.md
  src/domains/rtd-common/env/dev/terraform.tfvars
Labels: status: applied, env: dev

#479 Iid 29 allineamento config map
  src/domains/idpay-app/08_k8s_configmaps.tf
  src/domains/idpay-app/99_variables.tf
  src/domains/idpay-app/README.md
  src/domains/idpay-app/api_product/app_io/policy_io.xml.tpl
  src/domains/idpay-app/env/dev/terraform.tfvars
Labels: status: applied, env: dev

#482 [RTD-373] Add test result as response body
  src/api/rtd_sender_api_key_check/openapi.yml
  src/api/rtd_sender_mauth_check/openapi.yml
Labels: status: applied, env: dev, env: uat, env: prod

#488 [RTD-388] Enable Batch Service APIs to PROD environment
  src/env/prod/terraform.tfvars
Labels: status: applied, env: prod

#473 [TAE-139] Fix AdE ACK naming convention
  src/domains/tae-app/pipelines/ackIngestor.dataflow
Labels: env: uat

#491 [TAE-144] Align storage accounts
  src/domains/tae-common/02_blob_storage.tf
Labels: status: applied, env: dev, env: uat

#472 [RTD-323] AdE ACK upload endpoint
  src/README.md
  src/api/rtd_deposit_ade_ack/azureblob_policy.xml
  src/api/rtd_deposit_ade_ack/openapi.yml
  src/api_rtd.tf
Labels: status: applied, env: dev, env: uat, env: prod

#490 [RTD-268] Add file register collection
  src/README.md
  src/rtd_database.tf
Labels: status: applied, env: uat

#484 [TAE-143] Migrate blobstorage to v2
  src/storage.tf
Labels: status: applied, env: dev, env: uat, env: prod

#493 [TAE-88] Hash Sender Code for container name
  src/api/rtd_csv_transaction/create-sas-token-policy.xml
  src/api_rtd.tf
Labels: status: apply in progress

#483 [RTD-374] Create new hashed pan container
  src/README.md
  src/api/rtd_payment_instrument_manager/get-hashed-pans-policy-rev2.xml.tpl
  src/api_rtd.tf
  src/domains/rtd-app/08_pipeline.tf
  src/domains/rtd-app/99_variables.tf
  src/domains/rtd-app/README.md
  src/domains/rtd-app/env/dev/terraform.tfvars
  src/domains/rtd-app/env/uat/terraform.tfvars
  src/domains/rtd-app/pipelines/hashpan_csv_pipeline.json
  src/domains/rtd-common/04_datafactory.tf
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
  src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
  src/storage.tf
  src/variables.tf
Labels: status: applied, env: dev, env: uat

#492 [TAE-141] add step to project relevant sender ade ack fields
  src/domains/tae-app/07_datasets.tf
  src/domains/tae-app/README.md
  src/domains/tae-app/pipelines/ackIngestor.dataflow
  src/domains/tae-app/pipelines/ackIngestor.json
Labels: status: apply in progress

#489 IPE-241-pubblicazione-swagger-su-apim
  src/domains/idpay-app/04_apim_api_portal.tf
  src/domains/idpay-app/api/idpay_initiative/get-config-mcc.xml.tpl
  src/domains/idpay-app/api/idpay_initiative/get-config-transaction-rule.xml.tpl
  src/domains/idpay-app/api/idpay_initiative/openapi.initiative.yml
  src/domains/idpay-app/api/idpay_initiative/put-initiative-reward-draft.xml.tpl
  src/domains/idpay-app/api/idpay_initiative/put-initiative-reward.xml.tpl
  src/domains/idpay-app/api/idpay_initiative/simple-mock-policy.xml
  src/domains/idpay-common/99_variables.tf
  src/domains/idpay-common/README.md
Labels: status: applied, env: dev

#500 [RTD-410] Disable schema drifting
  src/domains/tae-app/08_pipeline.tf
  src/domains/tae-app/pipelines/ackIngestor.dataflow
  src/domains/tae-app/pipelines/aggregatesIngestor.json
  src/domains/tae-app/pipelines/aggregatesSchema.json
Labels: status: apply in progress

#504 [TAE-164] Modify aggregates ingestor trigger pattern
  src/domains/tae-app/08_pipeline.tf
Labels: status: applied

#503 [TAE-151] Avoid downloading ADEACK twice
  src/core/api/rtd_senderack_download_file/azureblob_policy.xml
Labels: status: applied

#506 [TAE-171] Whitelist IP
  src/core/env/prod/terraform.tfvars
Labels: status: applied, env: prod

#505 [TAE-167] Storage accounts observability
  src/domains/tae-common/02_blob_storage.tf
  src/domains/tae-common/99_variables.tf
  src/domains/tae-common/README.md
  src/domains/tae-common/env/dev/terraform.tfvars
  src/domains/tae-common/env/uat/terraform.tfvars
Labels: status: applied, env: dev, env: uat

#509 [TAE-172] Migrate cosmos in prod
  src/core/env/prod/terraform.tfvars
  src/domains/tae-common/env/prod/backend.ini
  src/domains/tae-common/env/prod/backend.tfvars
  src/domains/tae-common/env/prod/terraform.tfvars
Labels: status: applied, env: prod

#510 [RTD-426] Autoscaling Decrypter
  src/core/env/prod/terraform.tfvars
  src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
  src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
Labels: status: applied, env: uat, env: prod

#511 [TAE-173] Remove link with security logs
  src/domains/tae-common/01_keyvault.tf
Labels: status: applied, env: prod

#512 [TAE-174] Create prod conf
  src/domains/tae-app/01_network.tf
  src/domains/tae-app/README.md
  src/domains/tae-app/env/prod/backend.ini
  src/domains/tae-app/env/prod/backend.tfvars
  src/domains/tae-app/env/prod/terraform.tfvars
Labels: status: applied, env: prod

#513 [RTD-425] Increase partitions in eventhub rtd-platform-event
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
Labels: status: applied, env: uat, env: prod

#514 [RTD-432] change policy in sftp-retrieve to get ade ack from out cont…
  src/core/api/rtd_deposited_file_check/azureblob_policy.xml
  src/core/api/rtd_deposited_file_check/openapi.yml
  src/core/api_rtd.tf
Labels: status: applied, env: dev, env: uat, env: prod

#515 [RTD-433] increase the decrypter consumer timeout
  src/k8s/rtd_configmaps.tf
Labels: status: applied, env: dev, env: uat, env: prod

#516 [TAE-175] Fix comsmos permissions
  src/domains/tae-common/env/prod/terraform.tfvars
  src/k8s/rtd_configmaps.tf
Labels: status: applied, env: prod

#518 [RTD-438] add tmp container on blob storage
  src/core/README.md
  src/core/tae_storage.tf
Labels: status: apply in progress

#519 [RTD-439] update conversion map abi to fiscalCode
  src/core/api/rtd_abi_to_fiscalcode/policy.xml.tpl
Labels: status: applied, env: dev, env: uat, env: prod

#523 [RTD-446] add ICARD to conversion map abi-fiscalCode
  src/core/api/rtd_abi_to_fiscalcode/policy.xml.tpl
Labels: status: applied
